---
- name: restart frr
  ansible.builtin.systemd_service:
    name: frr
    state: restarted

- name: restart nm
  ansible.builtin.systemd_service:
    name: NetworkManager
    state: restarted

- name: restart haproxy
  ansible.builtin.systemd_service:
    name: haproxy
    state: restarted

- name: restart nm
  ansible.builtin.systemd_service:
    name: NetworkManager
    state: restarted

- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true


