---
k8s_url: https://pkgs.k8s.io/core:/stable:/
k8s_version: v1.35
k8s_packages:
- python3-kubernetes
- kubectl
- kubeadm
- kubelet

k8s_calico_version: 3.30.2
k8s_calico_url: "https://raw.githubusercontent.com/projectcalico/calico/v{{ k8s_calico_version }}/manifests/calico.yaml"
k8s_containerd_version: 2.3.0
k8s_runc_version: 1.4.2
k8s_cni_version: 1.9.1
k8s_helm_version: 4.2.0
k8s_cni_interface: eth1
k8s_package_urls:
- name: containerd
  url: "https://github.com/containerd/containerd/releases/download/v{{ k8s_containerd_version }}/containerd-{{ k8s_containerd_version }}-linux-amd64.tar.gz"
- name: runc
  url: "https://github.com/opencontainers/runc/releases/download/v{{ k8s_runc_version }}/runc.amd64"
- name: cni
  url: "https://github.com/containernetworking/plugins/releases/download/v{{ k8s_cni_version }}/cni-plugins-linux-amd64-v{{ k8s_cni_version }}.tgz"
- name: helm
  url: "https://get.helm.sh/helm-v{{ k8s_helm_version }}-linux-amd64.tar.gz"


k8s_repo_list:
- name: kubernetes
  description: "Kubernetes"
  baseurl: "{{ k8s_url }}{{ k8s_version }}/rpm"
  gpgkey: "{{ k8s_url }}{{ k8s_version }}/rpm/repodata/repomd.xml.key"
  exclude: "{{ k8s_packages }}"

k8s_api_address: "{{ ansible_host }}"
k8s_node_ip: "{{ ansible_host }}"
k8s_api_port: 6443
k8s_pod_network_cidr: "10.244.0.0/16"
k8s_service_cidr: "10.96.0.0/12"
k8s_init_cluster: false
