---
network_bridges: []
#- name: mgmt
#  state: present
#  ip4: 10.10.0.1/24

#- name: date
#  state: absent
#  method4: disabled
#  method6: disabled

network_packages:
  - frr

network_vxlans: []
#  - id: 200
#    loopback: 172.16.0.100
#    bridge: ext_api
#    state: present
