---
init_timezone: UTC
init_users: 
  - name: "admin"
    key: "Some public key"
    sudoers_rule: "ALL=(ALL) ALL"
    #password_hash: "Some hash value"

init_packages_update: False
init_kernel_update: False
init_packages_default:
  - wget
  - tmux
  - git
  - vim
  - bash-completion
  - policycoreutils-python-utils
  - net-tools
  - bind-utils
  - tcpdump
  - mtr
  - nc
  - nmap
  - curl
