---
init_timezone: UTC
init_hosts_group: all

init_packages_update: True
init_packages_default:
  - tmux
  - git
  - vim
  - bash-completion
  - policycoreutils-python-utils
  - net-tools
  - bind-utils
  - tcpdump
  - mtr
  - nc
  - nmap
  - curl
