---
- name: Configure VRF on border
  community.general.nmcli:
    type: vrf
    ifname: vrf_core
    table: 2000
    state: present
    conn_name: vrf_core
    method4: disabled
    method6: disabled
  when: "'border' in inventory_hostname"

- name: create bridge and vxlan on border
  ansible.builtin.shell: "ip link add br_anycast type bridge; ip link set br_anycast master vrf_core; ip link set br_anycast up; ip link add vxlan400 type vxlan id 400 dstport 4789 local 172.16.0.24 nolearning;  ip link set vxlan400 master br_anycast;  ip link set eth3 master vrf_core;  ip route add 150.150.150.0/24  dev eth3;ip link set vxlan400 up"
  when: "'border' in inventory_hostname"

- ansible.posix.sysctl:
    name: "net.ipv4.fib_multipath_hash_policy"
    value: '1'
    sysctl_set: true
    state: present
    reload: true
