---
- name: Install pip
  dnf:
    name: pip
    state: present
  when: "'str' in inventory_hostname"

- name: Install flask
  shell: pip install flask
  when: "'str' in inventory_hostname"

- name: Deploy test script python
  template:
    src: test.py.j2
    dest: /usr/local/sbin/teststr
    mode: "0755"
    owner: root
    group: root
  when: "'str' in inventory_hostname"
  notify: 
    - restart teststr

- name: Deploy teststr.service
  template:
    src: teststr.service.j2
    dest: /etc/systemd/system/teststr.service
  notify:
    - daemon reload
  when: "'str' in inventory_hostname"

- name: Ensure teststr.service is started and enabled
  systemd_service:
    name: teststr
    state: started
    enabled: true
  when: "'str' in inventory_hostname"
