---
- name: Create directories for cloud-init files
  file:
    path: "{{ vm_create_cloud_init_output_path }}"
    state: directory
    mode: "0755"

- name: Generate user-data file
  template:
    src: "{{ user_data_template }}"
    dest: "{{ cloud_init_output_path }}/user-data"

- name: Generate network-config file
  template:
    src: "{{ network_data_template }}"
    dest: "{{ cloud_init_output_path }}/network-config"

- name: Generate meta-data file
  template:
    src: "{{ meta_data_template }}"
    dest: "{{ cloud_init_output_path }}/meta-data"

