---
virt_provision_cloudinit_path: /storage/ssd01
  #vm_create_image_path: "/storage/hdd/almalinux_9_cloud_base_image.qcow2"
  #vm_create_network:
  #name: prod-routed
  #subnet: 10.10.0.0/24
  #gw: 10.10.0.1
  #ns_servers:
  #  - 10.10.0.1
  #search_domain: example.com
