---
# vars file for roles/vm_creation
#
cloud_init_output_path: "/storage/ssd"
pool_path: /storage/ssd
image_source_path: "/storage/hdd/almalinux_9_cloud_base_image.qcow2"
os_variant: "almalinux9"
network: prod-routed
gateway: 10.10.0.1
nameserver: 10.10.0.1
search_domain: cloudit.kz

