
- name: Configure VRF
  community.general.nmcli:
    type: vrf
    ifname: vrf_anycast
    table: 1000
    state: present
    conn_name: vrf_anycast
    method4: disabled
    method6: disabled
  when: "'lb' in inventory_hostname"

- ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Install haproxy
  ansible.builtin.dnf:
    name: haproxy
    state: present
  when: "'lb' in inventory_hostname"

- name: Deploy haproxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  when: "'lb' in inventory_hostname"
  notify:
    - restart haproxy

- name: Deploy systemd service haproxy
  ansible.builtin.template:
    src: haproxy.service.j2
    dest: /etc/systemd/system/haproxy.service
  when: "'lb' in inventory_hostname"
  notify:
    - daemon reload

- ansible.posix.sysctl:
    name: net.ipv4.tcp_l3mdev_accept
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Ensure haproxy is started and enabled
  systemd_service:
    name: haproxy
    state: started
    enabled: true
  when: "'lb' in inventory_hostname"
