---
- name: Install required packages
  ansible.builtin.dnf:
    name: frr #frr-stable-repo #https://rpm.frrouting.org/repo/frr-stable-repo.el9.noarch.rpm
    state: present
    disable_gpg_check: true

- name: Enable FRR daemons
  ansible.builtin.lineinfile:
    path: /etc/frr/daemons
    regexp: '^{{ item }}='
    line: '{{ item }}=yes'
  loop:
    - bgpd
    - zebra
    - bfdd
  notify:
    - restart frr

- name: Deploy frr conf for managed nodes
  ansible.builtin.template:
    src: "{{ inventory_hostname_short }}.frr.conf"
    dest: /etc/frr/frr.conf
  ignore_errors: true
  tags: network.frr.config
  notify:
    - restart frr

- name: Ensure service frr is enabled and started
  ansible.builtin.systemd_service:
    name: frr
    state: started
    enabled: true

- name: Configure loopback interface
  community.general.nmcli:
    conn_name: lo
    conn_reload: true
    ip4:
      - "127.0.0.1/8"
      - "{{ loopback }}"
    state: present
  when: loopback is defined

- name: Configure VRF on border
  community.general.nmcli:
    type: vrf
    ifname: vrf_isp
    table: 2000
    state: present
    conn_name: vrf_isp
    method4: disabled
    method6: disabled
  when: "'border' in inventory_hostname"

- name: Configure static routing on client machine
  ansible.builtin.command: "ip route add 5.5.5.5 via 150.150.150.20 dev eth1"
  when: "'client' in inventory_hostname"

- name: Configure VRF
  community.general.nmcli:
    type: vrf
    ifname: vrf_lb
    table: 1000
    state: present
    conn_name: vrf_lb
    method4: disabled
    method6: disabled
  when: "'lb' in inventory_hostname"

- name: Configure bridge devices for virtual machines
  community.general.nmcli:
    autoconnect: true
    method4: "{{ item['method4'] | default('disabled') }}"
    method6: "{{ item['method6'] | default('disabled') }}"
    autoconnect_priority: 999
    conn_name: "br_{{ item['name'] }}"
    conn_reload: true
    ifname: "br_{{ item['name'] }}"
    ip4: "{{ item['ip4'] | default(omit) }}"
    state: "{{ item['state'] | default('present') }}"
    stp: false
    type: bridge
    master: "{{ item['master'] | default(omit) }}"
    slave_type: "{{ item['slave_type'] | default(omit) }}"
  loop: "{{ network_bridges }}"
  when: network_bridges | length > 0
  tags: network.bridge
  notify: 
    - restart nm

- name: Create vxlans
  ansible.builtin.shell: "ip link add vxlan{{ item['id']}} type vxlan id {{  item['id'] }} dstport {{ item['dstport'] }} local {{ item['loopback'] }} nolearning; ip link set vxlan{{ item['id'] }} master br_{{ item['bridge'] }} ;ip link set vxlan{{ item['id']}} up; ip link set br_{{ item['bridge'] }} up" 
  loop: "{{ network_vxlans }}"
  when: network_vxlans | length > 0
  tags: network.vxlan

- name: create bridge and vxlan on border
  ansible.builtin.shell: "ip link add br_anycast type bridge; ip link set br_anycast master vrf_isp; ip link set br_anycast up; ip link add vxlan400 type vxlan id 400 dstport 4789 local 172.16.0.24 nolearning;  ip link set vxlan400 master br_anycast;  ip link set eth3 master vrf_isp;  ip route add 150.150.150.0/24  dev eth3;ip link set vxlan400 up; sysctl net.ipv4.fib_multipath_hash_policy=1"
  when: "'border' in inventory_hostname"



- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: restart frr
  ansible.builtin.systemd_service:
    name: frr
    state: restarted
  tags:
    - never
    - frr.restart
