---
- name: Install pip
  dnf:
    name: pip
    state: present
  when: "'lb' in inventory_hostname or 'str' in inventory_hostname"

- name: Install flask
  shell: pip install flask
  when: "'lb' in inventory_hostname or 'str' in inventory_hostname"

- name: Deploy test script python
  template:
    src: anycast.py.j2
    dest: /usr/local/sbin
  when: "'lb' in inventory_hostname or 'str' in inventory_hostname"

