---
- name: Create virtual disk
  command:
    cmd: "qemu-img create -b {{ vms_image }} -f qcow2 -F qcow2 {{ item['disk']['path'] }}/{{ item['name'] }}.qcow2 {{ item['disk']['size'] ~ 'G' }}"
  args:
    creates: "{{ item['disk']['path'] }}/{{ item['name'] }}.qcow2"
  loop: "{{ vms }}"

