---
- name: Check if source image exists
  stat:
    path: "{{ vms_image }}"
  register: __vms_image

- name: Fail if source image does not exist
  fail:
    msg: "Source image not found at {{ vms_image }}"
  when: not __vms_image.stat.exists
