---
- name: Get all VMS on the hypervisor
  command:
    cmd: "virsh list --all --name"
  register: __vms_virsh_list

- name: Extract all VM list from virsh command output
  set_fact:
    __vms_on_node: "{{ __vms_virsh_list.stdout_lines | list }}"

- debug:
    var: __vms_on_node

- name: Create VM
  command: >
    virt-install
    --name {{ item.name }}
    --memory {{ item.memory }}
    --vcpus {{ item.vcpu }}
    --disk path={{ item.disk.path }}/{{ item.name }}.qcow2,format=qcow2
    --os-variant {{ item['os-variant'] }}
    --import
    --graphics vnc,listen=0.0.0.0
    --noautoconsole
    --autostart
    {% for net in item.networks %}
    --network bridge={{ net.bridge }},model=virtio
    {% endfor %}
    --cloud-init user-data={{ item.disk.path }}/{{ item.name }}-user-data,meta-data={{ item.disk.path }}/{{ item.name }}-meta-data,network-config={{ item.disk.path }}/{{ item.name }}-network-config
  when: item['name'] not in __vms_on_node
  loop: "{{ vms }}"
