---
- name: Ensure dir for cloud init is present
  file:
    path: "{{ vmc_cloudinit_path }}"
    state: directory
    mode: "0755"

- name: Generate user-data file
  template:
    src: "user-data.j2"
    dest: "{{ vmc_cloudinit_path }}/user-data"

- name: Generate network-config file
  template:
    src: "network-config.j2"
    dest: "{{ vmc_cloudinit_path }}/network-config"

- name: Generate meta-data file
  template:
    src: "meta-data.j2"
    dest: "{{ vmc_cloudinit_path }}/meta-data"
