---

- name: Create virtual disk
  command:
    cmd: "qemu-img create -b {{ image_source_path }} -f qcow2 -F qcow2 {{ pool_path }}/{{ volume_name }} {{ volume_size }} "
  args:
    creates: "{{ pool_path }}/{{ volume_name }}"


- name: Create virtual machine
  command:
    cmd: >
      virt-install
      --name={{ domain }}
      --disk path={{pool_path}}/{{ volume_name }},format=qcow2
      --os-variant={{ os_variant }}
      --network network={{ network }}
      --graphics vnc,listen=127.0.0.1 --noautoconsole
      --ram={{ ram_in_mb }}
      --vcpus={{ vcpus }}
      --autostart
      --console pty,target_type=serial
      --cloud-init user-data={{ cloud_init_output_path }}/user-data,meta-data={{ cloud_init_output_path }}/meta-data,network-config={{ cloud_init_output_path }}/network-config

