---
- name: Create bridge devices for virtual machines
  community.general.nmcli:
    autoconnect: true
    autoconnect_priority: 999
    conn_name: "br-{{ item['name'] }}"
    conn_reload: true
    ifname: "br-{{ item['name'] }}"
    ip4: "{{ item['ip'] }}"
    state: "{{ item['state'] | default('present') }}"
    stp: false
    type: bridge
    zone: "{{ item['zone'] | default('internal') }}"
  loop: "{{ virt_network_bridges }}"
  
