! /etc/frr/frr.conf
hostname lb02.webcloud.kz
log syslog informational

router bgp 65032
 bgp router-id 172.16.0.32
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax

! Сосед - твой Leaf02
 neighbor LEAF peer-group
 neighbor LEAF remote-as external
 neighbor LEAF bfd
 neighbor 10.0.0.24 peer-group LEAF
 neighbor 10.0.0.46 peer-group LEAF


 address-family ipv4 unicast
  network 172.16.0.32/32
  neighbor LEAF activate
  maximum-paths 64
 exit-address-family

 address-family l2vpn evpn
  neighbor LEAF activate
  advertise-all-vni
  advertise-svi-ip
 exit-address-family

router bgp 65032 vrf vrf_lb
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family ipv6 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  advertise ipv6 unicast
 exit-address-family
exit
!

vrf vrf_lb
 ip router-id 172.16.0.32
 vni 400
exit-vrf


