! /etc/frr/frr.conf
hostname leaf03.webcloud.kz
log syslog informational

router bgp 65023
 bgp router-id 172.16.0.23
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax

 ! Аплинки к Spine
 neighbor SPINES peer-group
 neighbor SPINES remote-as external
 neighbor 10.0.0.16 peer-group SPINES
 neighbor 10.0.0.36 peer-group SPINES


 ! Даунлинки к LB
 neighbor LBS peer-group
 neighbor LBS remote-as external
 neighbor 10.0.0.27 peer-group LBS
 neighbor 10.0.0.47 peer-group LBS


 address-family ipv4 unicast
  network 172.16.0.23/32
  neighbor SPINES activate
  neighbor LBS activate
  maximum-paths 64
 exit-address-family
