! /etc/frr/frr.confd
frr version 8.5
frr defaults traditional
hostname spine02.webcloud.kz
log syslog informational
no ipv6 forwarding

router bgp 65012
 bgp router-id 172.16.0.12
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax
 
 ! Соседи - Leaf-коммутаторы
 neighbor LEAFS peer-group
 neighbor LEAFS remote-as external
 neighbor 10.0.0.33 peer-group LEAFS
 neighbor 10.0.0.35 peer-group LEAFS
 neighbor 10.0.0.37 peer-group LEAFS

 address-family ipv4 unicast
  network 172.16.0.12/32
  neighbor LEAFS activate
  maximum-paths 64
 exit-address-family
