! /etc/frr/frr.confd
frr version 8.5
frr defaults traditional
hostname spine01.webcloud.kz
log syslog informational
no ipv6 forwarding

router bgp 65011
 bgp router-id 172.16.0.11
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax
 
 ! Соседи - Leaf-коммутаторы
 neighbor LEAFS peer-group
 neighbor LEAFS remote-as external
 neighbor LEAFS bfd
 neighbor 10.0.0.13 peer-group LEAFS
 neighbor 10.0.0.15 peer-group LEAFS
 neighbor 10.0.0.17 peer-group LEAFS

 address-family ipv4 unicast
  network 172.16.0.11/32
  neighbor LEAFS activate
  maximum-paths 64
 exit-address-family

 address-family l2vpn evpn
  neighbor LEAFS activate
  advertise-all-vni
 exit-address-family
