---
- ansible.builtin.import_tasks: install.yml
  tags: firewalld.install

- ansible.builtin.import_tasks: rich_rules.yml
  tags: firewalld.rich_rules

- ansible.builtin.import_tasks: services.yml
  tags: firewalld.services


- name: Ensure firewalld service started and enable
  ansible.builtin.systemd_service:
    name: "firewalld"
    state: "{{ firewalld['state'] }}"
    enabled: "{{ firewalld['enabled'] }}"
    masked: "{{ firewalld['masked'] }}"
  when: firewalld | length != 0

- ansible.builtin.import_tasks: unmanaged_objects.yml
  tags: firewalld.unmanaged_objects

