---
- name: Configure firewalld ports
  ansible.posix.firewalld:
    permanent: "{{ item['permanent'] | default(true) }}"
    state: "enabled"
    zone: "{{ item['zone'] }}"
    offline: "{{ item['offline'] | default(true) }}"
    port: "{{ item['port'] }}"
    immediate: "{{ item['immediate'] | default(true) }}"
  loop: "{{ firewalld_ports }}"
  when: firewalld_services | length != 0
