---
- name: Configure firewalld protocols
  ansible.posix.firewalld:
    permanent: "{{ item['permanent'] | default(true) }}"
    state: "enabled"
    zone: "{{ item['zone'] }}"
    offline: "{{ item['offline'] | default(true) }}"
    protocol: "{{ item['name'] }}"
    immediate: "{{ item['immediate'] | default(true) }}"
  loop: "{{ firewalld_protocols }}"
  when: firewalld_protocols | length != 0
