---
- import_tasks: dnf.yml
  tags: init.dnf

- import_tasks: time.yml
  tags: init.time

- import_tasks: epel.yml
  tags: init.epel

- import_tasks: packages.yml
  tags: init.packages

- import_tasks: host.yml
  tags: init.hosts

- import_tasks: bash_profile.yml
  tags: init.bash_profile
